# -*- coding: utf-8 -*-
"""LastVersion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pyzCLCZr9JAL_vwyDFc4pcYV1FQsLNLp
"""

!pip install -U spacy
!python -m spacy download en_core_web_sm
!pip install -U spacy-transformers
!pip install -U spacy-lookups-data

import json

TRAIN_DATA = [
    {"text": "Levothyroxine is used to treat hypothyroidism by replacing thyroid hormone in the body.", "entities": [(0, 14, "HypothyroidismTreatment DRUG"), (48, 65, "ThyroidHormoneReplacement")]},
    {"text": "Cephalexin is an antibiotic used to treat various bacterial infections like skin infections and urinary tract infections.", "entities": [(0, 9, "BacterialInfectionTreatment DRUG"), (45, 60, "SkinInfectionTreatment"), (65, 89, "UrinaryTractInfectionTreatment")]},
    {"text": "Prednisone is prescribed to reduce inflammation and suppress the immune system in conditions like arthritis and allergic reactions.", "entities": [(0, 9, "InflammationReduction DRUG"), (63, 72, "ArthritisTreatment"), (77, 95, "AllergicReactionSuppression")]},
    {"text": "Albuterol is used as a bronchodilator to relieve bronchospasm in conditions like asthma and chronic obstructive pulmonary disease (COPD).", "entities": [(0, 8, "BronchospasmRelief DRUG"), (64, 70, "AsthmaManagement"), (75, 109, "COPDManagement")]},
    {"text": "Hydrochlorothiazide is a diuretic used to treat high blood pressure and fluid retention (edema).", "entities": [(0, 21, "HighBloodPressureTreatment DRUG"), (56, 67, "FluidRetentionTreatment")]},
    {"text": "Gabapentin is prescribed to treat nerve pain (neuropathic pain) and seizures.", "entities": [(0, 9, "NervePainTreatment DRUG"), (46, 59, "SeizureManagement")]},
    {"text": "Metoprolol is used to treat high blood pressure, chest pain (angina), and heart failure.", "entities": [(0, 9, "HighBloodPressureTreatment DRUG"), (38, 48, "ChestPainTreatment"), (53, 66, "HeartFailureTreatment")]},
    {"text": "Citalopram is an antidepressant used to treat depression and related mood disorders.", "entities": [(0, 9, "Antidepressant DRUG"), (40, 50, "DepressionTreatment"), (55, 70, "MoodDisorderTreatment")]},
    {"text": "Clarithromycin is an antibiotic used to treat bacterial infections such as pneumonia and sinusitis.", "entities": [(0, 13, "BacterialInfectionTreatment DRUG"), (48, 57, "PneumoniaTreatment"), (62, 71, "SinusitisTreatment")]},
    {"text": "Insulin is used to manage blood sugar levels in diabetes mellitus.", "entities": [(0, 7, "BloodSugarLevelManagement DRUG"), (39, 55, "DiabetesManagement")]},
    {"text": "Lisinopril is prescribed to treat high blood pressure and heart failure.", "entities": [(0, 9, "HighBloodPressureTreatment DRUG"), (37, 52, "HeartFailureTreatment")]},
    {"text": "Olanzapine is an antipsychotic medication used to treat schizophrenia and bipolar disorder.", "entities": [(0, 9, "Antipsychotic DRUG"), (47, 59, "SchizophreniaTreatment"), (64, 79, "BipolarDisorderTreatment")]},
    {"text": "Morphine is used to relieve severe pain, such as pain from heart attacks and major surgery.", "entities": [(0, 7, "PainRelief DRUG"), (39, 51, "SeverePainRelief"), (56, 70, "PostoperativePainRelief")]},
    {"text": "Doxycycline is an antibiotic used to treat infections caused by bacteria, including pneumonia and acne.", "entities": [(0, 10, "BacterialInfectionTreatment DRUG"), (65, 74, "PneumoniaTreatment"), (79, 84, "AcneTreatment")]},
    {"text": "Atorvastatin is used to lower cholesterol and reduce the risk of heart disease.", "entities": [(0, 13, "CholesterolReduction DRUG"), (51, 65, "HeartDiseaseRiskReduction")]},
    {"text": "Risperidone is prescribed to treat schizophrenia, bipolar disorder, and irritability associated with autism.", "entities": [(0, 10, "SchizophreniaTreatment DRUG"), (28, 42, "BipolarDisorderTreatment"), (47, 74, "AutismIrritabilityTreatment")]},
    {"text": "Furosemide is a diuretic used to treat fluid retention (edema) and high blood pressure.", "entities": [(0, 9, "FluidRetentionTreatment DRUG"), (44, 55, "HighBloodPressureTreatment")]},
    {"text": "Escitalopram is an antidepressant used to treat depression and generalized anxiety disorder (GAD).", "entities": [(0, 11, "Antidepressant DRUG"), (42, 52, "DepressionTreatment"), (57, 77, "GeneralizedAnxietyDisorderTreatment")]},
    {"text": "Metronidazole is an antibiotic used to treat infections caused by bacteria and parasites.", "entities": [(0, 13, "BacterialInfectionTreatment DRUG"), (58, 67, "ParasiticInfectionTreatment")]},
    {"text": "Dexamethasone is used to reduce inflammation in conditions like arthritis and severe allergies.", "entities": [(0, 12, "InflammationReduction DRUG"), (36, 45, "ArthritisTreatment"), (50, 66, "SevereAllergyTreatment")]},
    {"text": "Bupropion is prescribed to treat depression and seasonal affective disorder (SAD).", "entities": [(0, 9, "DepressionTreatment DRUG"), (44, 66, "SeasonalAffectiveDisorderTreatment")]},
    {"text": "Tramadol is used to relieve moderate to severe pain.", "entities": [(0, 7, "PainRelief DRUG"), (24, 41, "ModerateToSeverePainRelief")]},
    {"text": "Lansoprazole is used to reduce stomach acid production and treat conditions like gastroesophageal reflux disease (GERD).", "entities": [(0, 12, "StomachAcidReduction DRUG"), (57, 87, "GERDTreatment")]},
    {"text": "Fluoxetine is an antidepressant used to treat major depressive disorder (MDD) and panic disorder.", "entities": [(0, 10, "Antidepressant DRUG"), (41, 64, "MajorDepressiveDisorderTreatment"), (69, 83, "PanicDisorderTreatment")]},
    {"text": "Carvedilol is prescribed to treat high blood pressure, heart failure, and angina.", "entities": [(0, 9, "HighBloodPressureTreatment DRUG"), (37, 48, "HeartFailureTreatment"), (53, 59, "AnginaTreatment")]},
    {"text": "Amiodarone is used to treat irregular heartbeats (arrhythmias) and prevent sudden cardiac death.", "entities": [(0, 10, "ArrhythmiaTreatment DRUG"), (53, 74, "SuddenCardiacDeathPrevention")]},
    {"text": "Sildenafil is prescribed to treat erectile dysfunction and pulmonary arterial hypertension.", "entities": [(0, 9, "ErectileDysfunctionTreatment DRUG"), (44, 73, "PulmonaryArterialHypertensionTreatment")]},
    {"text": "Methotrexate is used to treat certain types of cancer, autoimmune diseases, and severe psoriasis.", "entities": [(0, 12, "CancerTreatment DRUG"), (48, 66, "AutoimmuneDiseaseTreatment"), (71, 85, "SeverePsoriasisTreatment")]},
    {"text": "Tamsulosin is used to treat symptoms of benign prostatic hyperplasia (BPH), such as difficulty urinating.", "entities": [(0, 10, "BPHSymptomRelief DRUG"), (63, 81, "UrinationDifficultyTreatment")]},
    {"text": "Losartan is prescribed to treat high blood pressure and reduce the risk of stroke in patients with hypertension.", "entities": [(0, 7, "HighBloodPressureTreatment DRUG"), (36, 55, "StrokeRiskReduction")]},
    {"text": "Pregabalin is prescribed to treat nerve pain (neuropathic pain) associated with diabetic neuropathy, fibromyalgia, and spinal cord injury.", "entities": [(0, 9, "NervePainTreatment DRUG"), (48, 66, "DiabeticNeuropathyPainTreatment"), (68, 81, "FibromyalgiaTreatment"), (86, 102, "SpinalCordInjuryPainTreatment")]},
    {"text": "Budesonide is used as an anti-inflammatory medication to treat asthma and inflammatory bowel disease (IBD).", "entities": [(0, 10, "AntiInflammatory DRUG"), (55, 61, "AsthmaTreatment"), (66, 86, "IBDTreatment")]},
    {"text": "Hydromorphone is prescribed to relieve severe pain, such as pain from cancer and major surgeries.", "entities": [(0, 12, "PainRelief DRUG"), (44, 50, "CancerPainRelief"), (55, 71, "PostoperativePainRelief")]},
    {"text": "Nitroglycerin is used to treat or prevent attacks of chest pain (angina).", "entities": [(0, 12, "ChestPainTreatment DRUG"), (50, 56, "AnginaPrevention")]},
    {"text": "Amitriptyline is prescribed to treat depression, neuropathic pain, and migraines.", "entities": [(0, 13, "DepressionTreatment DRUG"), (30, 44, "NeuropathicPainTreatment"), (49, 58, "MigraineTreatment")]},
    {"text": "Metformin is used to manage type 2 diabetes by controlling blood sugar levels.", "entities": [(0, 9, "Type2DiabetesManagement DRUG"), (43, 62, "BloodSugarLevelControl")]},
    {"text": "Amlodipine is prescribed to treat high blood pressure and chest pain (angina).", "entities": [(0, 9, "HighBloodPressureTreatment DRUG"), (38, 48, "ChestPainTreatment")]},
    {"text": "Salmeterol is used as a long-acting beta agonist to manage asthma and chronic obstructive pulmonary disease (COPD).", "entities": [(0, 10, "AsthmaManagement DRUG"), (55, 79, "COPDManagement")]},
    {"text": "Zolpidem is prescribed for the short-term treatment of insomnia (sleeplessness).", "entities": [(0, 7, "InsomniaTreatment DRUG"), (47, 60, "ShortTermInsomniaTreatment")]},
    {"text": "Valsartan is used to treat high blood pressure and heart failure.", "entities": [(0, 9, "HighBloodPressureTreatment DRUG"), (37, 48, "HeartFailureTreatment")]},
    {"text": "Levofloxacin is an antibiotic used to treat bacterial infections like pneumonia and urinary tract infections (UTIs).", "entities": [(0, 12, "BacterialInfectionTreatment DRUG"), (47, 56, "PneumoniaTreatment"), (61, 76, "UTITreatment")]},
    {"text": "Sertraline is an antidepressant used to treat depression, obsessive-compulsive disorder (OCD), and panic disorder.", "entities": [(0, 9, "Antidepressant DRUG"), (40, 56, "DepressionTreatment"), (61, 85, "OCDTreatment"), (90, 104, "PanicDisorderTreatment")]},
    {"text": "Mirtazapine is prescribed to treat depression and improve appetite in cancer patients.", "entities": [(0, 9, "DepressionTreatment DRUG"), (47, 58, "AppetiteImprovement"), (63, 78, "CancerPatientSupport")]},
    {"text": "Ciprofloxacin is an antibiotic used to treat infections caused by bacteria, including urinary tract infections (UTIs) and skin infections.", "entities": [(0, 13, "BacterialInfectionTreatment DRUG"), (58, 71, "UTITreatment"), (76, 91, "SkinInfectionTreatment")]},
    {"text": "Clopidogrel is used as an antiplatelet agent to reduce the risk of heart attacks and strokes.", "entities": [(0, 10, "Antiplatelet DRUG"), (51, 64, "HeartAttackPrevention"), (69, 76, "StrokePrevention")]},
    {"text": "Atenolol is prescribed to treat high blood pressure and chest pain (angina).", "entities": [(0, 8, "HighBloodPressureTreatment DRUG"), (37, 47, "ChestPainTreatment")]},
    {"text": "Desloratadine is an antihistamine used to relieve allergy symptoms like runny nose and sneezing.", "entities": [(0, 14, "AllergySymptomRelief DRUG"), (49, 66, "AllergySymptomRelief")]},
    {"text": "Esomeprazole is used to reduce stomach acid production and treat conditions like gastroesophageal reflux disease (GERD).", "entities": [(0, 12, "StomachAcidReduction DRUG"), (57, 87, "GERDTreatment")]},
    {"text": "Oxycodone is used to relieve moderate to severe pain.", "entities": [(0, 8, "PainRelief DRUG"), (25, 42, "ModerateToSeverePainRelief")]},
    {"text": "Duloxetine is prescribed to treat depression, generalized anxiety disorder (GAD), and chronic pain conditions like fibromyalgia.", "entities": [(0, 9, "DepressionTreatment DRUG"), (40, 54, "GeneralizedAnxietyDisorderTreatment"), (59, 72, "ChronicPainTreatment"), (77, 89, "FibromyalgiaTreatment")]},
    {"text": "Hydroxyzine is used as an antihistamine to relieve itching and anxiety.", "entities": [(0, 10, "Antihistamine DRUG"), (45, 52, "ItchingRelief"), (57, 64, "AnxietyRelief")]}
    ]

with open('data.json', 'w') as f:
    json.dump(TRAIN_DATA, f)

import spacy
from spacy.training.example import Example
import random

# Veri setinizi yükleyin
with open('data.json', 'r') as f:
    TRAIN_DATA = json.load(f)

# Varsayılan İngilizce modelini yükleyin
nlp = spacy.load("en_core_web_sm")

# Modeldeki entity recognizer bileşenini alın
ner = nlp.get_pipe("ner")

# Yeni etiketler ekleyin
for entry in TRAIN_DATA:
    for ent in entry.get("entities"):
        ner.add_label(ent[2])

# Lookups data yükleyin
import spacy.lookups
lookups = spacy.lookups.load_lookups("en", ["lexeme_norm"])

# Diğer bileşenlerin geçici olarak devre dışı bırakılması
unaffected_pipes = [pipe for pipe in nlp.pipe_names if pipe != "ner"]

# Modeli eğitme
with nlp.disable_pipes(*unaffected_pipes):
    optimizer = nlp.begin_training()
    for i in range(20):
        random.shuffle(TRAIN_DATA)
        losses = {}
        for entry in TRAIN_DATA:
            doc = nlp.make_doc(entry["text"])
            example = Example.from_dict(doc, {"entities": entry["entities"]})
            nlp.update([example], losses=losses, drop=0.5, sgd=optimizer)
        print(losses)

# Eğitilen modeli kaydetme
nlp.to_disk("custom_model")

# Eğitilen modeli yükleme
nlp_custom = spacy.load("custom_model")

# Modeli test etme
text = """
Metformin is commonly used to treat type 2 diabetes.
Loratadine, on the other hand, helps relieve allergy symptoms such as runny nose and sneezing.
Ibuprofen is an anti-inflammatory used to reduce pain and inflammation.
Zolpidem is prescribed for treating insomnia, while Fluoxetine is effective in managing depression and panic attacks.
"""

doc = nlp_custom(text)

# Tanımlanan varlıkları yazdırma
for ent in doc.ents:
    print(ent.text, "|", ent.label_)

from spacy import displacy
displacy.render(doc, style="ent")